CREATE TABLE ABD_A.JURUSAN LIKE MASTER.JURUSAN;
CREATE TABLE ABD_A.STRATA LIKE MASTER.STRATA;

CREATE SCHEMA mhs;
CREATE TABLE mhs.MAHASISWA LIKE MASTER.MAHASISWA;

CREATE TABLE ABD_A.PROGRAM_STUDI LIKE MASTER.PROGRAM_STUDI;
CREATE TABLE ABD_A.SELEKSI_MASUK LIKE MASTER.SELEKSI_MASUK;

CREATE ALIAS ABD_A.FAK FOR ABD_A.FAKULTAS
CREATE ALIAS ABD_A.JUR FOR ABD_A.JURUSAN;
CREATE ALIAS ABD_A.STR FOR ABD_A.STRATA;
CREATE ALIAS ABD_A.PRO FOR ABD_A.PROGRAM_STUDI;
CREATE ALIAS ABD_A.SEL FOR ABD_A.SELEKSI_MASUK;
CREATE ALIAS mhs.MHS FOR ABD_A.MAHASISWA;

CREATE INDEX ABD_A.PRO_INDEX1 ON ABD_A.PROGRAM_STUDI
(PROGRAM_STUDI);
CREATE INDEX mhs.MHS_INDEX1 ON mhs.MAHASISWA (KOTA_LAHIR);
CREATE UNIQUE INDEX ABD_A.JUR_INDEX1 ON ABD_A.JURUSAN (JURUSAN);
CREATE UNIQUE INDEX ABD_A.STR_INDEX1 ON ABD_A.STRATA (STRATA);

INSERT INTO ABD_A.FAKULTAS (ID_FAKULTAS, FAKULTAS)
VALUES (NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Ekonomi & Bisnis'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Pertanian'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Peternakan'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Teknik'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Kedokteran'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Perikanan'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'MIPA'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Teknologi Pertanian'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Ilmu Sosial & Ilmu Politik'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Ilmu Budaya'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Kedokteran Hewan'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Kedokteran Gigi'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Ilmu Komputer'),
(NEXT VALUE FOR ABD_A.ID_FAKULTAS_SEQUENCE, 'Vokasi');
